/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Pokemon = IDL.Record({
  'isShiny' : IDL.Bool,
  'name' : IDL.Text,
  'isFemale' : IDL.Bool,
});
export const Payout = IDL.Record({
  'date' : IDL.Text,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'calculatePayout' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'logPayout' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'logPokecoinBalance' : IDL.Func([IDL.Nat], [], []),
  'logPokemon' : IDL.Func([IDL.Text, IDL.Bool, IDL.Bool], [], []),
  'recordMatchResult' : IDL.Func([IDL.Nat, IDL.Vec(Pokemon)], [], []),
  'searchShinyFemalePokemon' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Pokemon)],
      ['query'],
    ),
  'viewPayouts' : IDL.Func([], [IDL.Vec(Payout)], ['query']),
  'viewPokecoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Pokemon = IDL.Record({
    'isShiny' : IDL.Bool,
    'name' : IDL.Text,
    'isFemale' : IDL.Bool,
  });
  const Payout = IDL.Record({
    'date' : IDL.Text,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'calculatePayout' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'logPayout' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'logPokecoinBalance' : IDL.Func([IDL.Nat], [], []),
    'logPokemon' : IDL.Func([IDL.Text, IDL.Bool, IDL.Bool], [], []),
    'recordMatchResult' : IDL.Func([IDL.Nat, IDL.Vec(Pokemon)], [], []),
    'searchShinyFemalePokemon' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Pokemon)],
        ['query'],
      ),
    'viewPayouts' : IDL.Func([], [IDL.Vec(Payout)], ['query']),
    'viewPokecoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };