/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Payout {
  'date' : string,
  'currency' : string,
  'amount' : bigint,
}
export interface Pokemon {
  'isShiny' : boolean,
  'name' : string,
  'isFemale' : boolean,
}
export interface _SERVICE {
  'logPayout' : ActorMethod<[bigint, string, string], undefined>,
  'logPokecoinBalance' : ActorMethod<[bigint], undefined>,
  'logPokemon' : ActorMethod<[string, boolean, boolean], undefined>,
  'searchShinyFemalePokemon' : ActorMethod<[string], Array<Pokemon>>,
  'viewPayouts' : ActorMethod<[], Array<Payout>>,
  'viewPokecoinBalance' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];